#*********************************************************************
# Copyright (c) Intel Corporation 2020
# SPDX-License-Identifier: Apache-2.0
#*********************************************************************/

# This is a basic workflow to help you get started with Actions

name: Docs-Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
permissions:
  contents: read

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    permissions:
      contents: write # for Git to git push
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: "3.11"
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          pip install -r ./requirements.txt --require-hashes
          mkdocs build --strict
      #checkout the gh-pages branch
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          path: "to-be-published"
          ref: "gh-pages"
      #copy the built site content
      - name: Copy
        if: ${{ github.ref == 'refs/heads/main' }}
        run: cp -rlf site/* ./to-be-published/
      #publish it
      - name: Publish content
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          MESSAGE: ${{github.event.head_commit.message}}
        run: |
          cd ./to-be-published
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m 'ci: ${{env.MESSAGE}}'
          git push origin gh-pages
